.TH GECRIT "1" "July 2011" "gEcrit 2.7"
.SH NAME
gecrit \- a python text editor
.SH SYNOPSIS
\fBgecrit\fR [\fIfilename\fR]
.SH DESCRIPTION
gEcrit is a Python text editor. It implements all the usual features found in
a capable editor, as well as a plugin system that allows easy expansion. It
comes with plugins such as a terminal emulator, a code refactoring tool based
on pyTidy, etc.
